---
title: "Description of the Assessment Models in MSEtool"
subtitle: "Development, Testing and Implementation of Management Procedures for Data-Rich Fisheries (v1.1)"
author: "Tom Carruthers (<t.carruthers@oceans.ubc.ca>) 
         Adrian Hordyk  (<a.hordyk@oceans.ubc.ca>),
         Quang Huynh (<q.huynh@oceans.ubc.ca>)"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: true
    number_sections: true
  #  toc: true
  #  number_sections: true    
  #rmarkdown::pdf_vignette:
vignette: >
  %\VignetteIndexEntry{Assessment}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({ TeX: { equationNumbers: {autoNumber: "all"} } });
</script>

<style type="text/css">

body{ /* Normal  */
   font-size: 12px;
}
td {  /* Table  */
   font-size: 8px;
}
h1 { /* Header 1 */
 font-size: 18px;
 color: DarkBlue;
}
h2 { /* Header 2 */
 font-size: 15px;
 color: DarkBlue;
}
h3 { /* Header 3 */
 font-size: 14px;
 color: DarkBlue;
}
code.r{ /* Code block */
  font-size: 10px;
}
pre { /* Code block */
  font-size: 10px
}
</style>


```{r set options, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
knitr::opts_chunk$set(dpi=85)
options(width = 650)
```

<br>

# Delay-Difference (DD) Model

## Growth
Growth in weight-at-age $w_a$ follows the recursive Brody equation:
$$w_{a+1} = \rho + \tilde\alpha w_a.$$
If weight is also described by the equation 
$$w_a = W_{\infty}(1 - \exp[K\{a-a_0\}])^b,$$ 
then $\tilde\alpha$ is solved in the limiting case where $w_a = w_{a+1} = w_{\infty}$ as $t \rightarrow \infty$,
$$\tilde\alpha = W_{\infty}(1 - \rho). $$
After substitution, 
$$\rho = \dfrac{w_{a+1} - W_{\infty}}{w_a - W_{\infty}}.$$
Here, $a = k+1$ was arbitrarily chosen to calculate $\rho$ where $k$ is the age of knife-edge selectivity. From catch and effort data alone, the age corresponding to the length of 50% maturity is chosen for $k$.

## Dynamics equations
The population biomass $B_t$ and abundance $N_t$ in year $t$ is given by
$$ \begin{align}
B_{t+1} &= s_t(\tilde{\alpha} N_t + \rho B_t) + w_k R_t\\
N_{t+1} &= s_tN_t + R_t,
\end{align}$$
where $w_k$ is the weight of recruits at age $k$ and $R_t$ is the recruitment in the next section, and $s_t$ is survival expressed as
$$ s_t = (1 - u_t)\exp(-M), $$
where $u_t$ is the annual harvest rate and $M$ is the instantaneous natural mortality rate. By conditioning the model on effort $f_t$, the harvest rate is
$$ u_t = 1 - \exp(-qf_t), $$
where $q$ is the estimated catchability coefficient and $f_t$ is the effort in year $t$. The predicted catch is 
$$\hat{C}_t = \hat{u}_t B_t $$
The log-likelihood $L$ of the observed catch $C_t$ over years $t = 1, ..., T$, assuming a lognormal distribution, is
$$L(C_t;u_{MSY}, MSY, q, \sigma)\propto -T \log\sigma - 0.5\sum_{t=1}^{T}\left(\dfrac{\log(C_t/\hat{C}_t)}{\sigma}\right)^2,$$
where $\sigma$ is the standard deviation of the lognormal distribution.

## Derivation of stock-recruit parameters from MSY and UMSY estimates
### Beverton-Holt relationship
Assuming a Beverton-Holt stock recruit relationship, then recruitment at age $k$ is:
$$ R_{t+k} = \dfrac{\alpha B_t(1 - u_t)}{1 + \beta B_t(1 - u_t)}.$$
From $MSY$ and $u_{MSY}$ estimates, then the stock-recruit parameters $\alpha$ and $\beta$ are:
$$ \begin{align}
\alpha &= (1 - u_{MSY})^{-2}(u_{MSY} \phi'_{MSY} + \phi_{MSY})^{-1}\\
\beta &= \dfrac{u_{MSY}}{MSY}\left(\alpha\phi_{MSY} - \dfrac{1}{1 - u_{MSY}}\right)
\end{align}$$
where $\phi_{MSY}$ and $\phi'_{MSY}$ are the biomass-per-recruit and derivative of biomass-per-recruit
with respect to $u$, respectively, evaluated at $u_{MSY}$:
$$\phi_{MSY} = \dfrac{\alpha s_{MSY} + w_k(1 - s_{MSY})}{(1 - s_{MSY})^2}$$
and
$$
\phi'_{MSY} = -\exp(-M)\left(\dfrac{\tilde\alpha + \phi_{MSY}(1 + \rho - 2\rho s_{MSY})}{(1 - \rho s_{MSY})(1 - s_{MSY})} +
\dfrac{\tilde\alpha s_{MSY}}{(1 - \rho s_{MSY})(1 - s_{MSY})^2} - \dfrac{\phi_{MSY}}{1-s_{MSY}}
\right)
$$
where $s_{MSY} = (1 - u_{MSY})\exp(-M)$. To obtain $\phi_{MSY}$, the equilibrium equation for biomass, $B_{MSY} = s_{MSY}(\tilde{\alpha} N_{MSY} + \rho B_{MSY}) + w_k R_{MSY}$, is solved for $B_{MSY}/R_{MSY}$ where $N_{MSY} = R_{MSY}/(1 - s_{MSY})$.

To derive $\alpha$ and $\beta$, let the equilibrium yield $Y$ and recruitment be a function of $u$ 
$$Y = u B = u \phi_u R$$
where
$$ R = \dfrac{\alpha \phi_u(1-u) - 1}{\beta \phi_u(1-u)}$$
Set $\frac{dY}{du} = 0$ and solve for $\alpha$ ($u$ by definition is $u_{MSY}$). In the equation above, $\beta$ is solved
for when $Y = MSY$, $\phi_u = \phi_{MSY}$, and $u = u_{MSY}$.

### Ricker equation
Assuming a Ricker stock-recruit relationship, then recruitment is:
$$ R_{t+k} = \alpha B_t(1 - u_t)\exp[-\beta B_t(1 - u_t)]$$
From $MSY$ and $u_{MSY}$ estimates, then the stock-recruit parameters $\alpha$ and $\beta$ are:
$$ \begin{align}
\alpha &= \dfrac{1}{\phi_{MSY}(1-u_{MSY})}\exp\left(u_{MSY} - \dfrac{u_{MSY}(1-u_{MSY})\phi'_{MSY}}{\phi_{MSY}}\right)\\
\beta &= \dfrac{u_{MSY}\log[\alpha\phi_{MSY}(1-u_{MSY})]}{MSY(1-u_{MSY})}
\end{align}$$
Similar to the Beverton-Holt version, $\alpha$ and $\beta$ are derived by solving the equilibrium yield equation $Y = u B = u \phi_u R$ and taking its derivative for $MSY$ based reference points, where
$$ R= \dfrac{\log(\alpha\phi_u[1-u])}{\beta \phi_u(1-u)}.$$
Set $\frac{dY}{du} = 0$ and solve for $\alpha$ ($u$ by definition is $u_{MSY}$). In the equation above, $\beta$ is solved
for when $Y = MSY$ and $u = u_{MSY}$.

## State-space version
The recruitment is
$$ R_t = E[R_t] \exp(-\delta_t - 0.5 \tau^2)$$
where $E[R_t]$ is the recruitment predicted by the Beverton-Holt or Ricker equation and $\delta_t \sim N(0, \tau^2)$ are
recruitment deviations. 


# Surplus-production (SP) model

$$B_{t+1} = B_t + P_t - C_t$$
where
$$P_t = \gamma MSY \left(\dfrac{B_t}{K}-\left[\dfrac{B_t}{K}\right]^n\right)$$

where 
$$\gamma = \dfrac{1}{n-1}n^{n/(n-1)}$$ is a function of $K$ is the carrying capacity given by 

$$\hat{I}_t = \hat{q} \hat{B}_t $$

The log-likelihood $L$ of the observed index $I_t$ over years $t = 1, ..., T$, assuming a lognormal distribution, is
$$L(I_t;u_{MSY}, MSY, q, \sigma)\propto -T \log\sigma - 0.5\sum_{t=1}^{T}\left(\dfrac{\log(I_t/\hat{I}_t)}{\sigma}\right)^2,$$

# Statistical catch-at-age (SCA) model


